name: Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Check licenses
        run: |
          export LICENSE_YEAR=$(date +%Y)
          make ci-check-licenses
